In [1]:
import numpy as np
array=np.random.randint(1,100,9)
array

array([30,  3, 89, 45, 79,  2, 33, 13, 21])

In [2]:
np.sqrt(array)

array([5.47722558, 1.73205081, 9.43398113, 6.70820393, 8.88819442,
       1.41421356, 5.74456265, 3.60555128, 4.58257569])

In [3]:
array.ndim

1

In [5]:
new_array=array.reshape(3,3)
new_array

array([[30,  3, 89],
       [45, 79,  2],
       [33, 13, 21]])

In [6]:
new_array.ndim

2

In [7]:
new_array.ravel()

array([30,  3, 89, 45, 79,  2, 33, 13, 21])

In [9]:
newm=new_array.reshape(3,3)
newm

array([[30,  3, 89],
       [45, 79,  2],
       [33, 13, 21]])

In [10]:
newm[2,1:3]

array([13, 21])

In [11]:
newm[1:2,1:3]

array([[79,  2]])

In [12]:
new_array[0:3,0:0]

array([], shape=(3, 0), dtype=int32)

In [13]:
new_array[0:2,0:1]

array([[30],
       [45]])

In [14]:
new_array[0:3,0:1]

array([[30],
       [45],
       [33]])

In [15]:
new_array[1:3]

array([[45, 79,  2],
       [33, 13, 21]])